### ISSUE TITLE
Install Mailchimp to work to collect email address

### ISSUE THREAD

**Issue by davidkartuzinski** [davidkartuzinski/ellieplatformsite#34]
These instructions will do: https://www.pythonstacks.com/blog/post/integrating-mailchimp-django/

**Comment by bbelderbos** [comment]
This is still a TODO right? Are you going to make a POST request to mailchimp upon capturing an email on your platform?

**Comment by davidkartuzinski** [comment]
@bbelderbos - This is now done. This is on the other new repo. The PR is here: https://github.com/open-apprentice/ellieplatform-website/pull/5, what I did was try two of the PyPi packages but neither worked, so I just copied the HTML and JavaScript from Mailchimp and made a template, https://github.com/open-apprentice/ellieplatform-website/pull/5, this was super simply, easy to maintain and effective!

**Comment by bbelderbos** [comment]
OK cool. I only see html in that PR, shouldn't you store the entry in your DB to signal to your system which user went on the Mailchimp email list?

**Comment by davidkartuzinski** [comment]
> OK cool. I only see html in that PR, shouldn't you store the entry in your DB to signal to your system which user went on the Mailchimp email list?

@bbelderbos - This is a great question. The short answer is, "no". I don't particularly want to signal or track this. Here is why: I don't want to optimize for it.  Collecting emails is sort of an indicator of interest but not very strong. The two indicators I want to test are people who think they are going to pay for the sass or people who are downloading the software from GitHub.  If the sass payments are valued at 50 points for example, for a 50 monthly. And the downloads are worth 20 points. An email may be worth 1/10 of a point. And a like or comment, for example, worth 0 points. 

The book, The Right It, really explains this kind of POV.

So I do want to collect the emails, but it's more of a vanity metric at this point. However, I will measure the funnel and conversion using other analytics as this is valuable info.

**Comment by bbelderbos** [comment]
I need to read that book! Thanks for the reminder :)
OK makes sense then, thanks
