### ISSUE TITLE
Host the website on the internet and set up continouos deployment

### ISSUE THREAD

**Issue by davidkartuzinski** [davidkartuzinski/ellieplatformsite#38]
1. Change the DNS for the domain name
2. set up the database on the server
3. Set up and bring django to the server via github.
4. setup continuous deployment whenever there is a PR on github.
5. set up cloudinary for the images - https://cloudinary.com/documentation/django_integration

**Comment by bbelderbos** [comment]
@davidkartuzinski how is this coming along?

**Comment by davidkartuzinski** [comment]
@bbelderbos - I created a new issue in the new repo: https://github.com/open-apprentice/ellieplatform-website/issues/11#issue-931456008 - essentially I tried and failed. So for the moment, I am updated the server manually.
